---

- hosts: 172.31.15.217
  user: ubuntu
  become: yes
  gather_facts: true
  vars:

    release: '34'

  tasks:

    - name: Login to ECR

      shell: sudo aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 102414258269.dkr.ecr.ap-south-1.amazonaws.com

    - name: Pull image from ECR

      shell: sudo docker pull 102414258269.dkr.ecr.ap-south-1.amazonaws.com/docker-demo:{{ release }}

    - name: Run Docker image

      docker_container:

        name: docker-demo

        image: 102414258269.dkr.ecr.ap-south-1.amazonaws.com/docker-demo:{{ release }}

        networks:

          - name: springboot-mysql-net

        env:
            HOST: 172.31.15.217
            AWS_REGION: ap-south-1

        state: started

        restart_policy: always

        ports:

          - 8081:8080
...
