spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysqldb://mysqldb:3307/employeeDB
    username: root
    password: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
      init:
        mode: always

server:
  port: 8081
